github:
  username:
  password:
  email:
  token:
  key:
  cert:
docker:
  url:
    username:
    password:
    email:
    registry:
    token:
    key:
    cert:
kube:
  url:
  cluster:
  username:
  password:
  email:
  token:
  key:
  cert:
gcloud:
  username:
  password:
  region:
  zone:
  google_application_credentials:
  gcp_project:
  gke_cluster_name:
  container_name:
  sql_database:
  sql_instance:
  sql_password:
  sql_project:
  sql_region:
  sql_user:
  server_service_account_name:
  db_access_service_account_name:
  cluster_name:
  bucket:
  token:
  key_path:
  cert_path:
  credentials: "~/.config/gcloud"


