//go:generate go fmt ./...
//go:generate go vet ./...
//go:generate go install ./...
//go:generate mamba walk grpc
//go:generate mamba walk gogo
//go:generate go fmt ./...
//go:generate go vet ./...
//go:generate go install ./...
//go:generate git add .
//go:generate git commit -m "successful go generate(no docker)🐍"
//go:generate git push origin master
//go:generate docker build -t "colemanword/mambagen:0.1.1"  .

package mamba
