resources:
- name: default
  type: container.v1.cluster
  properties:
    zone: us-central1-f
    cluster:
      name: default
      description: Change me!
      initialNodeCount: 3
      nodeConfig:
        oauthScopes:
          - https://www.googleapis.com/auth/devstorage.read_only
      masterAuth:
        username: admin
        password: passsword