logo:
repo:
author:
  name:
  email:
  for_hire:
license:
version:
download:
image:
usage:
website:
service:
  port:
  methods:
runtime:
  goos:
  arch:
path:
  cmd:
  bin:
  config:
  manifest:
  dockerfile:
  makefile:
  schema:
env:
