tools: #tools are downloaded if not present at runtime
  - url: "https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip"
    desitnation: "bin"
  - url: "github.com/gogo/protobuf/proto"
    desitnation: "bin"
  - url: "github.com/gogo/protobuf/protoc-gen-gofast"
    desitnation: "bin"
  - url: "github.com/gogo/protobuf/protoc-gen-goslick"
    desitnation: "bin"
  - url: "github.com/gogo/protobuf/gogoproto"
    desitnation: "bin"
  - url: "https://github.com/grpc/grpc"
    desitnation: "bin"
  - url: "github.com/kisielk/errcheck"
    desitnation: "bin"
  - url: "golang.org/x/tools/cmd/goimports"
    desitnation: "bin"
  - url: "github.com/golang/lint/golint"
    desitnation: "bin"
  - url: "github.com/golang/protobuf/protoc-gen-go"
    desitnation: "bin"
  - url: "https://github.com/saturnism/gcp-live-k8s-visualizer"
    desitnation: "bin"
  - url: "github.com/golang/protobuf/protoc-gen-go"
    desitnation: "bin"
  - url: "github.com/golang/protobuf/protoc-gen-go"
    desitnation: "bin"
  - url: "github.com/golang/protobuf/protoc-gen-go"
    desitnation: "bin"

scripts:
  prerun:
    first:
      name: protoc
      args: "--gofast_out=plugins=grpc:. my.proto"
      dir: "."
      env:

  postrun: